spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/opentelemetry
    username: username
    password: password

  sql:
    init:
      mode: always # to init db by running sql script in resources

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        default_schema: orders
        dialect: org.hibernate.dialect.PostgreSQLDialect